import 'package:commerce_x/Model/product_model.dart';

List<Product> product = [
  Product(
    id: 0,
    name: 'Hp Laptop',
    price: '17000',
    description: 'Gaming Laptop',
    image: 'assets/images/hp_gaming.png',
    isFavourite: true,
  ),
  Product(
    id: 1,
    name: 'Dell Laptop',
    price: '23000',
    description: 'Gaming Laptop',
    image: 'assets/images/dell_gaming.jpg',
    isFavourite: false,
  ),
  Product(
    id: 2,
    name: 'MSI Laptop',
    price: '27000',
    description: 'Gaming Laptop',
    image: 'assets/images/msi_gaming.png',
    isFavourite: true,
  ),
  Product(
    id: 3,
    name: 'Asus Laptop',
    price: '39000',
    description: 'Gaming Laptop',
    image: 'assets/images/asus_gaming.jpg',
    isFavourite: false,
  ),
  Product(
    id: 4,
    name: 'Acer Laptop',
    price: '42000',
    description: 'Gaming Laptop',
    image: 'assets/images/acer_gaming.png',
    isFavourite: false,
  ),
  Product(
    id: 5,
    name: 'Asus Laptop',
    price: '39000',
    description: 'Gaming Laptop',
    image: 'assets/images/asus_gaming.jpg',
    isFavourite: false,
  ),
  Product(
    id: 6,
    name: 'Acer Laptop',
    price: '42000',
    description: 'Gaming Laptop',
    image: 'assets/images/acer_gaming.png',
    isFavourite: false,
  ),
  Product(
    id: 7,
    name: 'Hp Laptop',
    price: '17000',
    description: 'Gaming Laptop',
    image: 'assets/images/hp_gaming.png',
    isFavourite: true,
  ),
];
List<Product> paymentMethod = [
  Product(
      id: 0,
      name: 'Paypal',
      price: '',
      description: '',
      image: 'assets/images/pp.png',
      isFavourite: false),
  Product(
      id: 1,
      name: 'VISA',
      price: '',
      description: '',
      image: 'assets/images/visa.png',
      isFavourite: false),
  Product(
      id: 2,
      name: 'MasterCard',
      price: '',
      description: '',
      image: 'assets/images/mc.png',
      isFavourite: false),
  Product(
      id: 3,
      name: 'Apple Pay',
      price: '',
      description: '',
      image: 'assets/images/ap.png',
      isFavourite: false),
  Product(
      id: 4,
      name: 'google Pay',
      price: '',
      description: '',
      image: 'assets/images/gp.jpg',
      isFavourite: false)
];
